export { default as Login } from "./Login"
export { default as Home } from "./Home"
export { default as SignUp } from "./SignUp"
export { default as Reset } from "./Reset"
export { default as SignIn } from "./SignIn"
export { default as AdviserPage } from "./AdviserPage"
export { default as ComapanyPage } from "./ComapanyPage"